config/routes.rb
Craigo::Application.routes.draw do
  resources :users do
    resources :posts
  end
  resources :posts
  
  root :to => 'posts#index'

  get "/login" => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get "/logout" => 'sessions#destroy'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post <ActiveRecord::Base
  attr_accessible :post_id, :title, :content, :user_id
  belongs_to :user
  has_many :comments
  validates_presence_of :title, :content
end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessible :username, :email, :password, :user_id
  
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :current_user
  
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def create
    @post = Post.new(title: params[:title], 
                    content: params[:content], 
                    user_id: current_user.id)

    if @post.save
      respond_to do |format|
        format.html {render partial: 'player'}
      end
    else
      respond_to do |format|
        format.js
      end
      # flash.now.alert = "Something went wrong with your post, try again"
      # render user_posts(current_user.id)
      # render page.js {'edit'}
    end
  end

  def show
    @post = Post.find_by_id(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_username(params[:username])
    if @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to :root
    else
      flash.alert "Invalid username or password"
      render login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    p params.inspect
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now.alert = "Something went wrong!!"
      render new_user_path
    end
  end

  def show
    @user = User.find(params[:id])    
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    if @user.save
      redirect_to user_url
    else
      render edit_user
    end
  end

  def destroy
    user = User.find(params[:id])
    session[:user_id] = nil
    user.destroy
    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craigo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <nav class="nav-bar">
    <% if !@current_user %>
    <%=link_to 'Login', login_path %>
    <%= link_to 'Sign Up', signup_path %>
    <%= link_to 'Click here for magic', root_url, class: "target" %>
    <% end %>
    <%= link_to 'Homepage', root_path %>
    <% if @current_user %> 
    You are logged in as <%= link_to @current_user.username, user_path(@current_user) %>
    <%= link_to 'Logout', logout_path %>
    <%= link_to 'Edit your profile', edit_user_url(@current_user) %>
    <% end %>
  </nav>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_new.html.erb
<%= form_tag user_posts_url(@current_user), class: "boom"  do |p| %>
<%= label_tag :title %>
<%= text_field_tag :title, nil, placeholder: "title"%>
<p><%= label_tag :content %></p>
<p><%= text_area_tag :content, nil, rows: 20, cols: 40, placeholder: "content"%></p>
<%= submit_tag "Submit Post" %>
<% end %> 

app/views/posts/_player.html.erb
<h1>Player! Player!</h1>

app/views/posts/index.html.erb
<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, post_path(post.id) %></li>
    <li><%= link_to post.user.username,  user_path(post.user.id) %></li>
  <%end%>
</ul>

app/views/posts/show.html.erb
<% if @current_user %>
<h5>Create a new post </h5>
<%= render 'new' %>
<% end %>
<h1><%=@post.title %></h1>
<h3><%=@post.content%></h3>
<h4><%= link_to @post.user.username, user_path(@post.user_id) %></h4>
<div class="add">
</div>

app/views/users/edit.html.erb
<h1> Edit your info! <%=@current_user.username %> </h1>
<%= form_for @current_user  do |f|%>
<%= f.label :username %>
<%= f.text_field :username, value: @current_user.username %>
<%= f.label :email %>
<%= f.text_field :email, value: @current_user.email %>
<%= f.label :password %>
<%= f.password_field :password, placeholder: "you should know this" %>
<%= f.submit("Edit my info") %>
<%end%>

<%= form_for @current_user, method: :delete do |f| %>
<%= f.submit("destroy yourself") %>
<% end %>

app/views/users/new.html.erb
<h3>Sign Up Below!</h3>

<%= form_for @user  do |f|%>
<%= f.label :username %>
<%= f.text_field :username, placeholder: "username" %>
<%= f.label :email %>
<%= f.text_field :email, placeholder: "email" %>
<%= f.label :password %>
<%= f.password_field :password, placeholder: "da secrets" %>
<%= f.submit("Sign me up") %>
<%end%>

<%if @user %>
<% @user.errors.each do |key, message|%>
<h1><%= key %> <%= message %></h1>
<%end%>
<%end%>

app/views/users/show.html.erb
<h1>Welcome to <%= @user.username %> 's Page</h1>

<% @user.posts.each do |post| %>
<ul>
  <li><%= link_to post.title, post_path(post.id)%></li>
  <li><%= post.content %></li>
</ul>
<%end%>